min-required-players: 1
countdown-seconds: 20
lobby-spawn:
  world: "world"
  x: 12.722
  y: -59.0
  z: 36.703
  yaw: 177.0
  pitch: 24.9
arenas:
  0:
    world: "world"
    x: 11.152
    y: -59.0
    z: 8.614
    yaw: -179.0
    pitch: 18.1
  1:
    world: "world"
    x: -0.695
    y: -59.0
    z: 8.7
    yaw: 179.2
    pitch: 28.6
winner-podium:
  world: "world"
  x: 0.885
  y: -59.0
  z: 35.680
  yaw: -179.2
  pitch: 23.7
