min-required-players: 1
countdown-seconds: 20
lobby-spawn:
  world: "world"
  x: 12.722
  y: -59.0
  z: 36.703
  yaw: 177.0
  pitch: 24.9
arenas:
  0:
    world: "arena_0"
    x: -2.988
    y: -60
    z: 1.994
    yaw: 40
    pitch: 10
  1:
    world: "arena_1"
    x: 3.012
    y: -60
    z: -5.9
    yaw: 48.2
    pitch: 11.1
winner-podium:
  world: "world"
  x: 0.885
  y: -59.0
  z: 35.680
  yaw: -179.2
  pitch: 23.7
